### ISSUE TITLE
photo gallery

### ISSUE THREAD

**Issue by amasson99** [amasson99/JEA-website#9]
When you can, see if the plug in that Kate found works and populate with SF photos on the site.  

Thanks 

-KG 

Kelly Glasscock, CJE |  Executive Director

Journalism Education Association 

Kansas State University 

105 Kedzie Hall 828 Mid-Campus Dr. S. Manhattan, KS 66506 

O 785•532•7822 | KellyRP@ksu.edu

**Comment by amasson99** [comment]
Currently inbetween jobs with laptops, slated to get a new macbook around aug 1, so I'll knock this out then

**Comment by amasson99** [comment]
http://jea.org/wp/blog/bwg_gallery/test-gallery/

@klgdigital26 Do you have the san fran photos? Same thing with headshots, I can swing by and grab them from you sometime

**Comment by KateJEA** [comment]
@amasson99 @klgdigital26 
Are we still going to be using this plugin?  If not, we should remove it from the site.

**Comment by klgdigital26** [comment]
I feel that we should use SmugMug instead of this plugin. If it will help
the site become more responsive to remove it, by all means, go ahead.


Because of all the hands that will be in the mix, I think it would be
easier to utilize smugmug instead of granting access to our site to use the
gallery feature. That being said, please take note that plugin as we might
have a use for it in the future.

Thanks,
-KG

**Comment by KateJEA** [comment]
Okay, sounds good.  I agree, if we're going to have lots of people posting to the gallery, I like the SmugMug idea better.
